apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agricultural-platform.fullname" . }}-secret
  labels:
    {{- include "agricultural-platform.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}